### PR TITLE
JENKINS-62319 - Help text asking for creating a folder before role is too hard to read

### PR DESCRIPTION
**Pull request by richbg**
#hacktoberfest

Attempt to resolve issue, make font bolder easier to read. 

Image capture after change:
folder-Text

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
Sounds reasonable

**Comment by AbhyudayaSharma** [comment]
@oleg-nenashev Hi! I'm seeing these `SocketTimeoutExceptions` on this PR and also on #64 and #63. I ran the tests on my machine (Windows with Java 11 and Java 8) and they run fine. Are these failures because of some instability on ci.jenkins.io? Or does this look to be some problem with the plugin?

This is the stack trace from the CI build:
```
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at hidden.jth.org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at hidden.jth.org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at hidden.jth.org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
	at hidden.jth.org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at hidden.jth.org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at hidden.jth.org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at hidden.jth.org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at hidden.jth.org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
	at hidden.jth.org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at hidden.jth.org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at hidden.jth.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at hidden.jth.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at hidden.jth.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at hidden.jth.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at hidden.jth.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at hidden.jth.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at com.gargoylesoftware.htmlunit.HttpWebConnection.getResponse(HttpWebConnection.java:192)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1397)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponse(WebClient.java:1315)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:394)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:315)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:463)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:448)
	at org.jvnet.hudson.test.HudsonTestCase$WebClient.goTo(HudsonTestCase.java:1612)
	at org.jvnet.hudson.test.HudsonTestCase$WebClient.goTo(HudsonTestCase.java:1600)
	at org.jvnet.hudson.test.HudsonTestCase$WebClient.executeOnServer(HudsonTestCase.java:1520)
	at org.jvnet.hudson.test.HudsonTestCase.executeOnServer(HudsonTestCase.java:1362)
	at org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyTestSuite.runGroupedTests(JellyTestSuiteBuilder.java:157)
	at org.jvnet.hudson.test.junit.GroupedTest.run(GroupedTest.java:51)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
```

**Review by AbhyudayaSharma — COMMENTED** [review]
Hi @richbg ! Thanks a lot! I think instead of adding the strong tag, maybe you can use the CSS `font-weight` property because according to MDN:

> Typically this element is rendered by default using a bold font weight. However, it should not be used simply to apply bold styling; use the CSS font-weight property for that purpose. Use the `<b>` element to draw attention to certain text without indicating a higher level of importance. Use the `<em>` element to mark text that has stress emphasis.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong

**Comment by richbg** [comment]
@AbhyudayaSharma  please have a look, reverted the change to the js and modified the css. 
Same result, the text  "Please create a folder before adding a folder role." is easier to read and should solve Jenkins-62319

**Review by AbhyudayaSharma — APPROVED** [review]

**Pull request merged**
